create table if not exists custom_simulations (
  id uuid primary key default gen_random_uuid(),
  user_id text,
  scenario text,
  domain text,
  reality_seed text,
  agent_count int,
  rounds int,
  platforms text[],
  llm_model text,
  parallel_gen int,
  status text default 'pending',
  mirofish_project_id text,
  mirofish_sim_id text,
  mirofish_task_id text,
  result jsonb,
  report_text text,
  round_logs jsonb,
  agent_breakdown jsonb,
  confidence int,
  primary_probability int,
  consensus_round int,
  runtime_seconds int,
  created_at timestamptz default now(),
  completed_at timestamptz
);
